# Generated by Django 5.2.3 on 2025-06-27 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electroapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.URLField(blank=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
