# Generated by Django 5.2.3 on 2025-06-27 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electroapp', '0002_product_delete_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(default='No description yet.'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=500),
        ),
    ]
